# Generated by Django 3.1.3 on 2020-11-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201102_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='ACCESSORY', max_length=255),
        ),
    ]
