# Generated by Django 3.1.3 on 2020-11-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('ACCESSORY', 'ACCESSORY'), ('VEHICLE', 'VEHICLE')], default='ACCESSORY', max_length=255),
        ),
    ]
