# Generated by Django 3.1.3 on 2020-11-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcontent',
            old_name='info_page_content',
            new_name='info_page_content_1',
        ),
        migrations.AddField(
            model_name='productcontent',
            name='info_page_content_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
