# Generated by Django 3.1.3 on 2020-11-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201102_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcontent',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
