# Generated by Django 3.1.3 on 2020-11-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201102_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontent',
            name='landing_page_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
