# Generated by Django 3.1.3 on 2020-11-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201102_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontent',
            name='features_page_content_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcontent',
            name='features_page_heading_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcontent',
            name='stats_page_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcontent',
            name='stats_page_heading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcontent',
            name='video_page_video_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
