# Generated by Django 3.1.3 on 2020-11-02 17:10

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201102_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontent',
            name='features_page_metrics_1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=core.models.get_default_list, size=None),
        ),
        migrations.AddField(
            model_name='productcontent',
            name='stats_page_metrics',
            field=models.JSONField(default=core.models.get_default_json),
        ),
    ]
