# Generated by Django 3.1.3 on 2020-11-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201102_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcontent',
            name='pricing_page_amount',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='pricing_page_emi',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
