# Generated by Django 3.1.3 on 2020-11-02 17:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201102_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcontent',
            name='stats_page_metrics',
            field=models.JSONField(blank=True, default=core.models.get_default_json),
        ),
    ]
