# Generated by Django 3.1.3 on 2020-11-02 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(default='VIRTUAL', max_length=32)),
                ('base_amount', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('gst_amount', models.IntegerField(default=0)),
                ('discount_amount', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('UserAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.useraddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
