# Generated by Django 3.1.3 on 2020-11-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='UserAddress',
            new_name='user_address',
        ),
    ]
