# Generated by Django 3.1.3 on 2020-11-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_useraddress_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='addless_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='addless_line_2',
            new_name='address_line_2',
        ),
    ]
