# Generated by Django 3.1.3 on 2020-11-21 14:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontent',
            name='features_page_main_stat',
            field=models.JSONField(blank=True, default=core.models.get_default_json),
        ),
        migrations.AddField(
            model_name='productcontent',
            name='info_4_bg_image_1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcontent',
            name='info_4_bg_image_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcontent',
            name='info_page_bg_image_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcontent',
            name='primary_color',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcontent',
            name='whats_more_bg_image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
