# Generated by Django 3.1.3 on 2020-11-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='frame_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
