# Generated by Django 3.1.3 on 2020-11-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='form_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
