# Generated by Django 3.1.3 on 2021-01-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_emailleadlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontent',
            name='stats_bg_image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcontent',
            name='whats_more_subtitle_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
