# Generated by Django 3.1.3 on 2021-01-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
