# Generated by Django 3.1.3 on 2021-01-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_testridebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='testridebooking',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testridebooking',
            name='scheduled_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
