# Generated by Django 3.1.3 on 2021-01-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20210106_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='city',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='email',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
