# Generated by Django 3.1.3 on 2021-03-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testridebooking',
            name='product',
        ),
        migrations.AddField(
            model_name='testridebooking',
            name='bike_name',
            field=models.CharField(default='doodle', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testridebooking',
            name='organisation_name',
            field=models.CharField(default='techpotato', max_length=255),
            preserve_default=False,
        ),
    ]
