# Generated by Django 3.1.3 on 2021-03-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20210318_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='emi_per_month',
            field=models.IntegerField(default=0),
        ),
    ]
