# Generated by Django 3.1.3 on 2021-03-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_blog_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='dealer_or_online',
            field=models.CharField(default='online', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warranty',
            name='purchase_date',
            field=models.DateField(default='2020-10-10'),
            preserve_default=False,
        ),
    ]
