# Generated by Django 3.1.3 on 2021-03-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20210327_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
