# Generated by Django 3.1.3 on 2021-04-16 15:10

import core.models
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_product_display_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=core.models.get_default_list, size=None),
        ),
    ]
