# Generated by Django 3.1.3 on 2021-04-16 15:21

import core.models
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20210416_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.JSONField(blank=True, default=core.models.get_default_json), blank=True, default=core.models.get_default_list, size=None),
        ),
    ]
