# Generated by Django 3.1.3 on 2021-04-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20210416_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
