# Generated by Django 3.1.3 on 2021-04-19 04:38

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20210416_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('discount_code', models.CharField(max_length=255, unique=True)),
                ('discount_percent', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'promocode',
            },
        ),
    ]
