# Generated by Django 3.1.3 on 2021-04-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20210426_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolors',
            options={'verbose_name': 'Product Colors'},
        ),
        migrations.AlterModelTable(
            name='productcolors',
            table='productColors',
        ),
    ]
