# Generated by Django 3.1.3 on 2021-04-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20210426_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolors',
            options={'verbose_name': 'Product Color', 'verbose_name_plural': 'Product Colors'},
        ),
    ]
