# Generated by Django 3.1.3 on 2021-05-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20210504_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancerequest',
            name='user',
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='dealer_or_online',
            field=models.CharField(default='no value', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='dealer_or_platform',
            field=models.CharField(default='no value', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='name',
            field=models.CharField(default='no value', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='phone',
            field=models.CharField(default='no value', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='purchase_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
