# Generated by Django 3.1.3 on 2021-05-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20210504_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityuser',
            name='dealer_or_platform',
        ),
        migrations.AddField(
            model_name='product',
            name='brochure',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
